### ISSUE TITLE
adjust to latest dependencie version

### ISSUE THREAD

**Issue by schlitzered** [yano3/puppet-cerebro#42]
the module depends on deprecated versions of:

camptocamp-systemd
puppet-archive
puppet-extlib
puppetlabs-stdlib

please update the module to allow the latest versions of these module.

**Comment by alexjfisher** [comment]
FWIW, these are all fixed in https://github.com/yano3/puppet-cerebro/pull/41
@yano3 Have you had a chance to look at that PR yet?

**Comment by yano3** [comment]
Updated in https://github.com/yano3/puppet-cerebro/pull/43
